### ISSUE TITLE
dynamodb-wrapper typings incompatible with typescript 2.5.2

### ISSUE THREAD

**Issue by Shadowblazen** [Shadowblazen/dynamodb-wrapper#6]
I have a typescript project that uses dynamodb-wrapper 1.4.0 and typescript 2.3.2. After upgrading this project to use typescript to 2.5.2, the following tsc errors appeared:

```
/node_modules/dynamodb-wrapper/index.d.ts(57,13):
error TS2411: Property 'partitionStrategy' of type '"EqualItemCount" | "EvenlyDistributedGroupWCU"' is not assignable to string index type 'IBatchWriteItemOption'.
/node_modules/dynamodb-wrapper/index.d.ts(58,13):
error TS2411: Property 'targetItemCount' of type 'number' is not assignable to string index type 'IBatchWriteItemOption'.
/node_modules/dynamodb-wrapper/index.d.ts(59,13):
error TS2411: Property 'targetGroupWCU' of type 'number' is not assignable to string index type 'IBatchWriteItemOption'.
/node_modules/dynamodb-wrapper/index.d.ts(60,13):
error TS2411: Property 'groupDelayMs' of type 'number' is not assignable to string index type 'IBatchWriteItemOption'.
```

Todo: fix errors in dynamodb-wrapper's typings file

Workaround (until this bug is fixed): in package.json, pin your version typescript to 2.3.2

**Comment by Shadowblazen** [comment]
Fixed in version 1.4.1
